### ISSUE TITLE
compile / build error

### ISSUE THREAD

**Issue by zryan3** [gyng/rust-raytracer#34]
I'm building on Ubuntu 14.04. When running `cargo build --release`, I get these errors

```    
Updating registry https://github.com/rust-lang/crates.io-index
 Downloading rustc-serialize v0.3.14
 Downloading num_cpus v0.2.5
 Downloading gcc v0.3.5
 Downloading time v0.1.25
 Downloading threadpool v0.1.4
 Downloading rand v0.3.8
 Downloading num v0.1.24
 Downloading libc v0.1.7
   Compiling threadpool v0.1.4
   Compiling libc v0.1.7
   Compiling rustc-serialize v0.3.14
   Compiling gcc v0.3.5
   Compiling num_cpus v0.2.5
   Compiling rand v0.3.8
   Compiling time v0.1.25
   Compiling num v0.1.24
   Compiling rust-raytracer v0.1.0 (file:///home/usr/extra/rust-raytracer)
src/util/import.rs:33:42: 33:60 error: type `str` does not implement any method in scope named `split_whitespace`
src/util/import.rs:33         let tokens: Vec<&str> = line[..].split_whitespace().collect();
                                                               ^~~~~~~~~~~~~~~~~~
src/util/import.rs:122:41: 122:59 error: type `str` does not implement any method in scope named `split_whitespace`
src/util/import.rs:122     let mut tokens: Vec<&str> = tex[..].split_whitespace().collect();
                                                               ^~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `rust-raytracer`.
```

**Comment by gyng** [comment]
The raytracer should compile in Rust 1.1 (and 1.2) nightly, and won't compile in its current state on Rust 1.0 stable. I don't think rust-raytracer compiles on stable now. What's your Rust version?

NIghtly was used as the raytracer was programmed while Rust was still not stable. Nightly (1.1) was then the recommended channel. Also due to this a bunch of unstable APIs are still being used, and stable doesn't let you use unstable APIs. I'm thinking of getting rust-raytracer to run on stable once Rust stable 1.1 lands. I'll make a note about this in the README.

To fix this specific error, you can try replacing `split_whitespace()` with `words()` and see how it goes.

**Comment by zryan3** [comment]
I replaced `splite_whistespace()` with `words()` but there seems to be additional errors:

```
cargo build --release
   Compiling rust-raytracer v0.1.0 (file:///home/usr/extra/rust-raytracer)
src/util/import.rs:33:42: 33:49 error: use of unstable library feature 'str_words': the precise algorithm to use is unclear
src/util/import.rs:33         let tokens: Vec<&str> = line[..].words().collect();
                                                               ^~~~~~~
src/util/import.rs:122:41: 122:48 error: use of unstable library feature 'str_words': the precise algorithm to use is unclear
src/util/import.rs:122     let mut tokens: Vec<&str> = tex[..].words().collect();
                                                               ^~~~~~~
src/raytracer/compositor/colorrgba.rs:78:5: 84:6 warning: method is never used: `from_packed_rgba`, #[warn(dead_code)] on by default
src/raytracer/compositor/colorrgba.rs:78     pub fn from_packed_rgba(color: u32) -> ColorRGBA<u8> {
src/raytracer/compositor/colorrgba.rs:79         let r = ((color >> 24) & 0xFF) as u8;
src/raytracer/compositor/colorrgba.rs:80         let g = ((color >> 16) & 0xFF) as u8;
src/raytracer/compositor/colorrgba.rs:81         let b = ((color >>  8) & 0xFF) as u8;
src/raytracer/compositor/colorrgba.rs:82         let a = ((color >>  0) & 0xFF) as u8;
src/raytracer/compositor/colorrgba.rs:83         ColorRGBA { r: r, g: g, b: b, a: a }
                                         ...
src/raytracer/compositor/colorrgba.rs:90:5: 92:6 warning: method is never used: `new_rgba`, #[warn(dead_code)] on by default
src/raytracer/compositor/colorrgba.rs:90     pub fn new_rgba(r: T, g: T, b: T, a: T) -> ColorRGBA<T> {
src/raytracer/compositor/colorrgba.rs:91         ColorRGBA { r: r, g: g, b: b, a: a }
src/raytracer/compositor/colorrgba.rs:92     }
src/main.rs:1:1: 1:63 error: unstable feature
src/main.rs:1 #![feature(collections, convert, core, exit_status, std_misc)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to 3 previous errors
Could not compile `rust-raytracer`.

To learn more, run the command again with --verbose.
```
I don't know enough about rust quite yet to debug them so I'll see if I can look into the nightly versions of rust to play around with and I'll see how that goes.

**Comment by infinityb** [comment]
This should compile on the stable now.

Regards,
